stages:
  - deploy

deploy:
  stage: deploy
  script:
    - ssh root@204.93.172.132 "cd /var/www/MedicalBox-provier-web && git clone https://gitlab.com/self-care/MedicalBox-provider-web"
 
  only:
    - main
